-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
REVOKE ALL ON TABLE public.profiles FROM authenticated;

REVOKE ALL ON TABLE public.profiles FROM postgres;

REVOKE ALL ON TABLE public.profiles FROM service_role;

GRANT ALL ON TABLE public.profiles TO authenticated;

GRANT ALL ON TABLE public.profiles TO postgres;

GRANT ALL ON TABLE public.profiles TO service_role;

REVOKE ALL ON TABLE public.service_types FROM authenticated;

REVOKE ALL ON TABLE public.service_types FROM postgres;

REVOKE ALL ON TABLE public.service_types FROM service_role;

GRANT ALL ON TABLE public.service_types TO authenticated;

GRANT ALL ON TABLE public.service_types TO postgres;

GRANT ALL ON TABLE public.service_types TO service_role;

REVOKE ALL ON TABLE public.processes FROM authenticated;

REVOKE ALL ON TABLE public.processes FROM postgres;

REVOKE ALL ON TABLE public.processes FROM service_role;

GRANT ALL ON TABLE public.processes TO authenticated;

GRANT ALL ON TABLE public.processes TO postgres;

GRANT ALL ON TABLE public.processes TO service_role;

